version: '3'

services:
  cppbuiltins:
    build:
      context: .
      args:
        - IMAGE_NAME=${IMAGE_NAME}
        - IMAGE_VERSION=${IMAGE_VERSION}
    image: lycantropos/cppbuiltins:0.2.0-alpha
    volumes:
      - ./src/:/opt/cppbuiltins/src/
      - ./tests/:/opt/cppbuiltins/tests/
      - ./README.md:/opt/cppbuiltins/README.md
      - ./requirements-setup.txt:/opt/cppbuiltins/requirements-setup.txt
      - ./requirements-tests.txt:/opt/cppbuiltins/requirements-tests.txt
      - ./setup.py:/opt/cppbuiltins/setup.py
      - ./pytest.ini:/opt/cppbuiltins/pytest.ini
    entrypoint: pytest
